### ISSUE TITLE
Unable to compile Makefile.

### ISSUE THREAD

**Issue by praksharma** [cwrowley/ibpm#13]
I am using ubuntu 20.04 LTS. I have all fftw library in place as directed in the manual. 
I am constantly getting the error in Makefile.
![image](https://user-images.githubusercontent.com/70601302/117008900-197b5980-ace3-11eb-8e8f-8fbe0cc67b7e.png)

**Comment by cwrowley** [comment]
What are the contents of your make.inc?  The default is that this is a symbolic link to the file make.inc.gcc, but this may need to be customized for your system.

**Comment by praksharma** [comment]
The haven't modified  anything. Yes make.inc is linking make.inc.gcc. What exactly I need to modify?
I am using Ubuntu 20.04 LTS, my gcc and g++ version is 9.3.0. I have installed the fftw library 3.3.9, as mentioned in the manual.

**Comment by dfloryan** [comment]
This is likely due to the use of tabs vs. spaces in make.inc. See the link below:
https://stackoverflow.com/questions/16931770/makefile4-missing-separator-stop

**Comment by praksharma** [comment]
Actually, if you go through make.inc or make.inc.gcc they have no indentation(tabs).
However, the Makefile in the root has lots of indentation. I tried to replace them with tabs, didn't work.

**Comment by praksharma** [comment]
Okay, finally someone helped me to solve the problem. We had a long discussion on stackexchange and [steeldriver](https://unix.stackexchange.com/users/65304/steeldriver) helped me out. Here is our full discussion https://unix.stackexchange.com/questions/648048/unable-to-make-file-in-linux-ubuntu-20-04-lts

Actually that is not how a symbolic link is made. This command can be used to make a symbolic link `ln -sf make.inc.gcc config/make.inc`. Now, i can use the package as directed in the manual.

**Comment by cwrowley** [comment]
Great—glad it is working now.
